excluded:
  - build
  - TiercadeCore/.build
  - TiercadeCore/.swiftpm
  - TiercadeCore/Package.swift
  - TiercadeCore/Tests
  - referencedocs

cyclomatic_complexity:
  warning: 7

# Allow longer files and type bodies for comprehensive test suites
file_length:
  warning: 600
  error: 800

type_body_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 1
    error: 1
  validates_start_with_lowercase: false
  excluded:
    - L1
    - L2
    - Lbg
    - Lw
    - Lk

