excluded:
  - build
  - TiercadeCore/.build
  - TiercadeCore/.swiftpm
  - TiercadeCore/Package.swift
  - TiercadeCore/Tests
  - referencedocs

cyclomatic_complexity:
  warning: 7

identifier_name:
  min_length:
    warning: 1
    error: 1
  validates_start_with_lowercase: false
  excluded:
    - L1
    - L2
    - Lbg
    - Lw
    - Lk

