# .swiftlint.yml
# Tiercade SwiftLint configuration (LLM-oriented, Swift 6)
# Consensus config from Claude + ChatGPT analysis (2025-11-30)

included:
  - Tiercade
  - TiercadeTests
  - TiercadeUITests
  - TiercadeCore/Sources
  - TiercadeCore/Tests

excluded:
  - build
  - DerivedData
  - .build
  - TiercadeCore/.build
  - TiercadeCore/.swiftpm
  - node_modules
  - referencedocs
  - "**/*.generated.swift"

# MARK: - SwiftFormat Owns Layout (Disable All Style Rules)

disabled_rules:
  # Whitespace/layout - SwiftFormat handles
  - trailing_whitespace
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - leading_whitespace
  - closure_end_indentation
  - closure_parameter_position
  - indentation_width
  - trailing_newline
  - trailing_semicolon

  # Spacing/punctuation - SwiftFormat handles
  - colon
  - comma
  - trailing_comma
  - no_space_in_method_call
  - operator_usage_whitespace
  - comment_spacing
  - switch_case_alignment
  - statement_position
  - attributes
  - opening_brace
  - closing_brace
  - multiline_arguments
  - multiline_parameters
  - multiline_function_chains
  - multiline_literal_brackets

  # Noise reduction - deployment_target fires on every @available matching min target
  - deployment_target

  # Project-specific
  - explicit_acl
  - todo
  - blanket_disable_command
  - identifier_name
  - type_name
  - multiple_closures_with_trailing_closure

# MARK: - Safety & Concurrency Rules (Opt-In)

opt_in_rules:
  # Swift 6 Concurrency
  - unhandled_throwing_task
  # Note: async_without_await disabled - triggers on protocol conformance requirements

  # SwiftUI Best Practices
  - private_swiftui_state

  # Safety (crash/retain prevention)
  - force_unwrapping
  - implicitly_unwrapped_optional
  - weak_delegate
  - unowned_variable_capture

  # Accessibility
  - accessibility_label_for_image
  - accessibility_trait_for_button

  # Performance
  - empty_count
  - empty_string
  - first_where
  - last_where
  - sorted_first_last
  - reduce_into
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - flatmap_over_map_reduce

  # Modern Swift idioms
  - shorthand_optional_binding
  - toggle_bool
  - joined_default_parameter
  - redundant_nil_coalescing
  - identical_operands
  - yoda_condition
  # Note: discouraged_optional_boolean/collection disabled - many intentional optional APIs
  - overridden_super_call

# MARK: - Analyzer Rules (CI Only)

analyzer_rules:
  - unused_declaration
  - unused_import

# MARK: - Metrics (LLM-friendly bounds)

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true

function_body_length:
  warning: 50
  error: 80
  ignores_comments: true
  ignores_empty_lines: true

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 600
  error: 800
  ignore_comment_only_lines: true

function_parameter_count:
  warning: 6
  error: 8
  ignores_default_parameters: true

nesting:
  type_level: 2
  function_level: 4
  check_nesting_in_closures_and_statements: true

line_length:
  warning: 120
  error: 180
  ignores_comments: true
  ignores_urls: true

# MARK: - Severity Overrides

force_cast:
  severity: error

force_try:
  severity: error

force_unwrapping:
  severity: warning

# MARK: - Deployment Targets (OS 26)

deployment_target:
  iOS_deployment_target: 26.0
  macOS_deployment_target: 26.0
  tvOS_deployment_target: 26.0

# MARK: - Custom Rules (LLM Mistake Prevention)

custom_rules:
  no_print_statements:
    regex: '^\s*print\s*\('
    message: "Remove print() before committing; use unified logging instead."
    severity: warning
    excluded:
      - ".*Tests.*"
      - ".*AppleIntelligence.*"
      - ".*Debug.*"
      - ".*AIGeneration.*"
      - ".*PromptTestRunner.*"
      - ".*AIChat.*"
      - ".*TiercadeApp.*"
      - ".*Toolbar.*"

  avoid_force_unwrap_after_await:
    regex: 'await[^\n]*!'
    message: "Avoid force-unwrapping results of async calls."
    severity: warning

  task_self_capture:
    regex: 'Task\s*\{[^}]*\bself\.'
    message: "Consider [weak self] or verify actor isolation for Task closures."
    severity: warning

  prefer_mainactor_over_dispatch:
    regex: 'DispatchQueue\.main\.async'
    message: "Prefer @MainActor or MainActor.run in Swift Concurrency."
    severity: warning

reporter: xcode
