excluded:
  - build
  - TiercadeCore/.build
  - TiercadeCore/.swiftpm
  - TiercadeCore/Package.swift
  - TiercadeCore/Tests
  - referencedocs

cyclomatic_complexity:
  warning: 8
  error: 12

# Allow longer files and type bodies for comprehensive test suites
file_length:
  warning: 600
  error: 800

type_body_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 1
    error: 1
  validates_start_with_lowercase: false
  excluded:
    - L1
    - L2
    - Lbg
    - Lw
    - Lk

# Quality-focused opt-in rules to enable when ready; kept commented so current runs stay aligned.
# opt_in_rules:
#   - explicit_acl  # Require explicit access control to prevent accidental scope changes during refactors.
#   - explicit_top_level_acl  # Ensure top-level declarations declare visibility, aiding module boundary clarity.
#   - explicit_self  # Enforce explicit self usage for clearer capture semantics in async/concurrency-heavy code.
#   - unused_declaration  # Flag dead APIs so agents don't rely on stale entry points.
#   - unused_import  # Remove unused imports to keep dependencies obvious for automated tooling.
#   - redundant_type_annotation  # Eliminate duplicate typing that obscures real logic changes.
#   - redundant_optional_initialization  # Detect unnecessary optional defaults that add noise to state structs.
#   - prefer_self_type_over_type_of_self  # Uphold Swift 6 idioms for actor and type references.
#   - typed_throwing_functions  # Require explicit error types to document failure contracts for agents.
#   - unneeded_parentheses_in_closure_argument  # Strip syntactic clutter that complicates diff-based reasoning.
