excluded:
  - build
  - TiercadeCore/.build
  - TiercadeCore/.swiftpm
  - TiercadeCore/Package.swift
  - TiercadeCore/Tests
  - TiercadeCore/Sources                  # Core logic has intentional force unwraps in sorting comparisons
  - TiercadeTests                         # Test files legitimately use force unwraps
  - TiercadeUITests
  - referencedocs
  - node_modules

# MARK: - Complexity Thresholds

cyclomatic_complexity:
  warning: 8
  error: 12

# Length limits aligned with AGENTS.md targets (overlays <~400, views <~600)
file_length:
  warning: 600
  error: 800
  ignore_comment_only_lines: true

type_body_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 80

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

# MARK: - Identifier Configuration

identifier_name:
  min_length:
    warning: 1
    error: 1
  validates_start_with_lowercase: false
  excluded:
    - L1
    - L2
    - Lbg
    - Lw
    - Lk

# Function parameter count suppression policy (see commit d910b22):
# - Acceptable: Helper functions with 8+ params where parameter objects would obscure intent
# - Prefer: Extract parameter objects (see RetryState pattern in ca46798)
# - REQUIRED: Document reasoning inline for future reviewers when suppressing

# MARK: - Disabled Rules

# High noise-to-signal ratio for this codebase:
disabled_rules:
  - explicit_acl                          # Generated 1,469 warnings; Swift's implicit internal is sufficient for app code
  - explicit_top_level_acl                # Generated 41 warnings; adds churn without catching real bugs in practice

# MARK: - Opt-In Rules

# Safety, concurrency, and modern Swift patterns:
opt_in_rules:
  # Swift 6 Concurrency (catches async bugs)
  - unhandled_throwing_task               # Flag throwing tasks without error handling

  # SwiftUI Best Practices
  - private_swiftui_state                 # Apple recommends @State always be private

  # Safety (crash/retain prevention)
  - force_unwrapping                      # Discourage dangerous ! unwraps
  - implicitly_unwrapped_optional         # Discourage Type! declarations
  - weak_delegate                         # Prevent delegate retain cycles
  - unowned_variable_capture              # Catch crash-prone unowned captures in closures

  # Accessibility (tvOS VoiceOver support per AGENTS.md)
  - accessibility_label_for_image         # Images need labels or .accessibilityHidden(true)
  - accessibility_trait_for_button        # Buttons need proper accessibility traits

  # Modern Swift Patterns (performance/clarity)
  - empty_count                           # isEmpty over count == 0
  - first_where                           # first(where:) over filter().first
  - shorthand_optional_binding            # Swift 5.7+ if let foo syntax

# MARK: - Analyzer Rules

# NOTE: These only run with 'swiftlint analyze' (requires compilation).
# Without CI, run manually: swiftlint analyze --compiler-log-path build.log
analyzer_rules:
  - unused_declaration                    # Flag dead code after refactors
  - unused_import                         # Remove unused imports

# MARK: - Staged for Future

# Large initial diff risk - enable after targeted cleanup:
#   - explicit_self                       # Clearer capture semantics in async code
#   - sorted_imports                      # Diff hygiene (low value for solo dev)
#   - redundant_type_annotation           # Eliminate duplicate typing
#   - prefer_self_type_over_type_of_self  # Swift 6 idioms
