import Foundation

// MARK: - AI Generation Error

/// Typed errors for AI item generation failures.
internal enum AIGenerationError: Error, Sendable {
    /// The current platform doesn't support Apple Intelligence features
    case platformNotSupported

    /// The generation request has invalid parameters
    case invalidRequest(reason: String)

    /// The AI generation process failed
    case generationFailed(underlyingError: Error)

    /// User-friendly error message for toast display
    internal var userMessage: String {
        switch self {
        case .platformNotSupported:
            return "AI generation requires macOS 26+ or iOS 26+"
        case .invalidRequest(let reason):
            return reason
        case .generationFailed:
            return "Failed to generate items. Please try again."
        }
    }
}

// MARK: - AI Generation Request

/// Captures user input for an AI item generation request.
///
/// This model represents the parameters needed to generate a list of items
/// using Apple Intelligence. It includes validation logic to ensure the
/// description is non-empty and the count is within valid bounds.
internal struct AIGenerationRequest: Sendable {
    internal let description: String
    internal let itemCount: Int
    internal let timestamp: Date

    /// Validates that the request has a non-empty description and valid count range.
    internal var isValid: Bool {
        !description.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        && itemCount >= 5
        && itemCount <= 100
    }
}

// MARK: - AI Generated Item Candidate

/// Represents an AI-generated item awaiting user review and selection.
///
/// Items are generated by Apple Intelligence and presented to the user for review.
/// All items default to selected state, allowing users to deselect unwanted items
/// before importing into their tier list draft.
internal struct AIGeneratedItemCandidate: Identifiable, Hashable, Sendable {
    internal let id: UUID
    internal let name: String
    internal var isSelected: Bool  // Mutable for toggle operations
    internal let generatedAt: Date

    /// Creates a new candidate item with default selected state.
    ///
    /// - Parameters:
    ///   - name: The name of the generated item
    ///   - isSelected: Whether the item is selected (default: true)
    init(name: String, isSelected: Bool = true) {
        self.id = UUID()
        self.name = name
        self.isSelected = isSelected
        self.generatedAt = Date()
    }
}
