import Foundation

// MARK: - AI Generation Request

/// Captures user input for an AI item generation request.
///
/// This model represents the parameters needed to generate a list of items
/// using Apple Intelligence. It includes validation logic to ensure the
/// description is non-empty and the count is within valid bounds.
struct AIGenerationRequest: Sendable {
    let description: String
    let itemCount: Int
    let timestamp: Date

    /// Validates that the request has a non-empty description and valid count range.
    var isValid: Bool {
        !description.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        && itemCount >= 5
        && itemCount <= 100
    }
}

// MARK: - AI Generated Item Candidate

/// Represents an AI-generated item awaiting user review and selection.
///
/// Items are generated by Apple Intelligence and presented to the user for review.
/// All items default to selected state, allowing users to deselect unwanted items
/// before importing into their tier list draft.
struct AIGeneratedItemCandidate: Identifiable, Hashable, Sendable {
    let id: UUID
    let name: String
    var isSelected: Bool  // Mutable for toggle operations
    let generatedAt: Date

    /// Creates a new candidate item with default selected state.
    ///
    /// - Parameters:
    ///   - name: The name of the generated item
    ///   - isSelected: Whether the item is selected (default: true)
    init(name: String, isSelected: Bool = true) {
        self.id = UUID()
        self.name = name
        self.isSelected = isSelected
        self.generatedAt = Date()
    }
}
